spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  resources:
    add-mappings: true
server:
  address: 0.0.0.0
  port: 8893